name: 'Skip Duplicate Actions'
description: 'Skip duplicate workflow-runs. Cancel outdated workflow-runs.'
author: fkirc
branding:
  icon: 'stop-circle'
  color: 'white'
inputs:
  github_token:
    description: 'Your GitHub Access Token'
    required: true
  cancel_others:
    description: 'If true, then workflow-runs from outdated commits will be cancelled'
    required: false
    default: 'true'

outputs:
  should_skip:
    description: 'true if the current run is a duplicate workflow-run. This should be evaluated for either individual steps or entire jobs.'
runs:
  using: 'node12'
  main: 'dist/index.js'
