name: 'Skip Duplicate Actions'
description: 'Skip duplicate workflow-runs. Skip or ignore specific paths. Cancel outdated workflow-runs.'
author: 'fkirc'
branding:
  icon: 'stop-circle'
  color: 'white'
inputs:
  github_token:
    description: 'Your GitHub Access Token'
    required: true
    default: ${{ github.token }}
  paths_ignore:
    description: 'A JSON-array with ignored path patterns, e.g. something like ["**/README.md", "**/docs/**"]'
    required: false
    default: '[]'
  paths:
    description: 'A JSON-array with path patterns, e.g. something like ["platform-specific/**"]'
    required: false
    default: '[]'
  cancel_others:
    description: 'If true, then workflow-runs from outdated commits will be cancelled'
    required: false
    default: 'false'
  skip_after_successful_duplicate:
    description: 'If true, skip if an already finished duplicate run can be found'
    required: false
    default: 'true'
  do_not_skip:
    description: 'A JSON-array with triggers that should never be skipped'
    required: false
    default: '["workflow_dispatch", "schedule"]'
  concurrent_skipping:
    description: 'One of never, same_content, same_content_newer, outdated_runs, always'
    required: true
    default: 'never'
outputs:
  should_skip:
    description: 'Returns true if the current run can be safely skipped. This should be evaluated for either individual steps or entire jobs.'
  successful_duplicate:
    description: 'If the current run is skipped because a successful duplicate has been found, information about the successful duplicate will be returned here.'
runs:
  using: 'node12'
  main: 'dist/index.js'
